### PR TITLE
Add support for mnx.io Manta, bump version

### PR DESCRIPTION
**Pull request by nshalman**
Obviously if you have no desire to maintain this, please feel free to close this PR.

### CODE REVIEW

**Comment by bahamas10** [comment]
thank you! and sorry for the late response.

I don't use this anymore so i probably won't be able to meaningfully maintain this.  If you are interested I can add you as a maintainer for the code :) or if anyone from MNX i'm happy to add as a maintainer or even transfer the repo to if it's useful!

**Comment by nshalman** [comment]
FYI @bahamat @danmcd

**Comment by bahamat** [comment]
You can transfer the repo to me, then I can transfer it to our new org. I’ll also need info on publishing it.

**Comment by bahamas10** [comment]
@bahamat ty, the transfer is in progress.

I haven't published it in 9 years so i'm very rusty.  I can access my google developer console for the plugin but don't see any obvious way to transfer ownership / add a contributor.

**Comment by bahamas10** [comment]
FYI somewhat relevant, i also wrote this https://github.com/bahamas10/sos but never got around to trying to PR for smartos or pkgin or whatever, but this is something I found useful on SmartOS and still use on my home lab

**Comment by bahamat** [comment]
You can give that one to me too, if you like.

**Comment by bahamas10** [comment]
@bahamat transferred!

**Pull request merged**
